# Generated by Django 4.1.4 on 2023-01-18 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='media/default', upload_to='media/mango_photo')),
                ('info', models.TextField(blank=True)),
                ('released', models.DateField()),
                ('description', models.TextField()),
                ('genre', models.ManyToManyField(related_name='%(app_label)s_%(class)s_genre', to='mango_card.genremango')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mango_card.typemango')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mango_card.mango')),
            ],
        ),
    ]
